### ISSUE TITLE
如何运行ckb-miner-avx512？

### ISSUE THREAD

**Issue by jiangxianliang007** [nervosnetwork/ckb-cuckoo-miner-avx512#1]
已编译好ckb-miner ，在运行的时候报错 Config Error: Error { inner: ErrorInner { kind: Custom, line: None, col: 0, message: "missing field `rpc_url`", key: ["miner"] } }

ckb-miner 同级目录下也有ckb-miner.toml 配置文件。
![image](https://user-images.githubusercontent.com/24754263/62521279-e7b13680-b861-11e9-8482-a98eb29c07da.png)

**Comment by cool007zqw** [comment]
用源码里的里的[ckb-miner.toml](https://github.com/nervosnetwork/ckb-cuckoo-miner-avx512/blob/master/ckb-miner.toml)

**Comment by timmyz** [comment]
> 用源码里的里的[ckb-miner.toml](https://github.com/nervosnetwork/ckb-cuckoo-miner-avx512/blob/master/ckb-miner.toml)

```
ERROR miner  rpc call get_block_template error: Json(Error("missing field `data_hash`", line: 0, column: 0))
```

**Comment by jiangxianliang007** [comment]
> > 用源码里的里的[ckb-miner.toml](https://github.com/nervosnetwork/ckb-cuckoo-miner-avx512/blob/master/ckb-miner.toml)
> 
> ```
> ERROR miner  rpc call get_block_template error: Json(Error("missing field `data_hash`", line: 0, column: 0))
> ```

已经可以跑了，多谢。
